# Data Manipulation

In [2]:
import torch
x = torch.arange(12, dtype = torch.float32)
x


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [14]:
x.numel()

12

In [15]:
x.shape

torch.Size([12])

### transform our vector x whose shape is (12,) to a matrix X with shape
(3, 4)

In [17]:
X = x.reshape(3, 4)
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [19]:
X = x.reshape(4, 3)
X

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])

In [5]:
X = x.reshape(3, -1)
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [22]:
torch.zeros((2, 3, 4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [23]:
torch.ones((2, 3, 4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

### creates a tensor with elements drawn from a standard Gaussian (normal) distribution with mean 0 and standard deviation 1

In [24]:
torch.randn(3, 4)

tensor([[ 0.7093,  2.1770, -0.3698,  1.0267],
        [-0.6223,  0.4705, -0.9547, -0.6483],
        [-0.5937,  1.5572,  0.8196,  0.9603]])

In [6]:
X[-1], X[1:3]

(tensor([ 8.,  9., 10., 11.]),
 tensor([[ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]))

In [29]:
torch.exp(x)

tensor([1.0000e+00, 2.7183e+00, 7.3891e+00, 2.0086e+01, 5.4598e+01, 1.4841e+02,
        4.0343e+02, 1.0966e+03, 2.9810e+03, 8.1031e+03, 2.2026e+04, 5.9874e+04])

In [33]:
x = torch.tensor([2, 3, 4])
y = torch.tensor([3, 4, 5])
x + y, x - y, x * y, x / y

(tensor([5, 7, 9]),
 tensor([-1, -1, -1]),
 tensor([ 6, 12, 20]),
 tensor([0.6667, 0.7500, 0.8000]))

In [7]:
X = torch.arange(12, dtype=torch.float32).reshape((3,4))
Y = torch.tensor([[0, 34, 56, 34], [46, 37, 50, 3], [100, 20, 60, 5]])
torch.cat((X, Y), dim=0), torch.cat((X, Y), dim=1)

(tensor([[  0.,   1.,   2.,   3.],
         [  4.,   5.,   6.,   7.],
         [  8.,   9.,  10.,  11.],
         [  0.,  34.,  56.,  34.],
         [ 46.,  37.,  50.,   3.],
         [100.,  20.,  60.,   5.]]),
 tensor([[  0.,   1.,   2.,   3.,   0.,  34.,  56.,  34.],
         [  4.,   5.,   6.,   7.,  46.,  37.,  50.,   3.],
         [  8.,   9.,  10.,  11., 100.,  20.,  60.,   5.]]))

In [8]:
X == Y

tensor([[ True, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [9]:
X.sum()

tensor(66.)

In [10]:
a = torch.arange(3).reshape((3, 1))
b = torch.arange(2).reshape((1, 2))
a, b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [11]:
Z = torch.zeros_like(Y)
print('id(Z):', id(Z))
Z[:] = X + Y
print('id(Z):', id(Z))

id(Z): 2489062844640
id(Z): 2489062844640


In [12]:
before = id(X)
X += Y
id(X) == before

True

In [13]:
A = X.numpy()
B = torch.from_numpy(A)
type(A), type(B)

(numpy.ndarray, torch.Tensor)

In [14]:
a = torch.tensor([3.5])
a, a.item(), float(a), int(a)

(tensor([3.5000]), 3.5, 3.5, 3)