# Algebra


### Scalar

In [4]:
import torch
x =torch.tensor(6.0)
y = torch.tensor(3.0)
x + y,  x - y, x * y, x /y

(tensor(9.), tensor(3.), tensor(18.), tensor(2.))

# Vector

In [6]:
X = torch.arange(5)
X

tensor([0, 1, 2, 3, 4])

In [7]:
X[1]

tensor(1)

In [8]:
len(X)

5

# Matrices

In [14]:
A = torch.arange(9).reshape(3, 3)
A

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

### Transponse

In [15]:
A.T

tensor([[0, 3, 6],
        [1, 4, 7],
        [2, 5, 8]])

### Symmetric Matrice

In [16]:
A == A.T

tensor([[ True, False, False],
        [False,  True, False],
        [False, False,  True]])