# Algebra


### Scalar

In [2]:
import torch
x =torch.tensor(6.0)
y = torch.tensor(3.0)
x + y,  x - y, x * y, x /y

(tensor(9.), tensor(3.), tensor(18.), tensor(2.))

# Vector

In [6]:
X = torch.arange(5)
X

tensor([0, 1, 2, 3, 4])

In [7]:
X[1]

tensor(1)

In [8]:
len(X)

5

# Matrices

In [14]:
A = torch.arange(9).reshape(3, 3)
A

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

### Transponse

In [15]:
A.T

tensor([[0, 3, 6],
        [1, 4, 7],
        [2, 5, 8]])

### Symmetric Matrice

In [16]:
A == A.T

tensor([[ True, False, False],
        [False,  True, False],
        [False, False,  True]])

### Tensor

In [4]:
torch.arange(24).reshape(2, 3, 4)

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

In [9]:
A = torch.arange(6, dtype=torch.float32).reshape(2, 3)
A
B =A.clone()
A,A +B

(tensor([[0., 1., 2.],
         [3., 4., 5.]]),
 tensor([[ 0.,  2.,  4.],
         [ 6.,  8., 10.]]))

### Hadamard product

In [10]:
A * B

tensor([[ 0.,  1.,  4.],
        [ 9., 16., 25.]])

In [11]:
a = 2
X = torch.arange(24).reshape(2, 3, 4)
a + X, (a * X).shape

(tensor([[[ 2,  3,  4,  5],
          [ 6,  7,  8,  9],
          [10, 11, 12, 13]],
 
         [[14, 15, 16, 17],
          [18, 19, 20, 21],
          [22, 23, 24, 25]]]),
 torch.Size([2, 3, 4]))

### Reduction

In [13]:
X =torch.arange(3, dtype=torch.float32)
X, X.sum()

(tensor([0., 1., 2.]), tensor(3.))

In [15]:
A.shape, A.sum()

(torch.Size([2, 3]), tensor(15.))

In [17]:
A, A.shape, A.sum(axis=0)

(tensor([[0., 1., 2.],
         [3., 4., 5.]]),
 torch.Size([2, 3]),
 tensor([3., 5., 7.]))

In [18]:
A, A.shape, A.sum(axis=1)

(tensor([[0., 1., 2.],
         [3., 4., 5.]]),
 torch.Size([2, 3]),
 tensor([ 3., 12.]))

In [22]:
A.sum(axis=[0, 1]), A.sum(),A.sum(axis=[0, 1]) == A.sum()

(tensor(15.), tensor(15.), tensor(True))

In [25]:
A.mean(), A.sum() / A.numel()

(tensor(2.5000), tensor(2.5000))

In [27]:
A

tensor([[0., 1., 2.],
        [3., 4., 5.]])

In [30]:
sum_A = A.sum(axis = 1, keepdim=True)
sum_A,sum_A.shape

(tensor([[ 3.],
         [12.]]),
 torch.Size([2, 1]))

In [32]:
A / sum_A

tensor([[0.0000, 0.3333, 0.6667],
        [0.2500, 0.3333, 0.4167]])

In [33]:
A.cumsum(axis=0)

tensor([[0., 1., 2.],
        [3., 5., 7.]])

In [34]:
A.cumsum(axis=1)

tensor([[ 0.,  1.,  3.],
        [ 3.,  7., 12.]])