# Introduction Lab

In [2]:
print('fit a model with', 11, 'variables')
x = [3, 4, 5]
x

[3, 4, 5]

In [3]:
y = [4, 9, 7]
x + y

[3, 4, 5, 4, 9, 7]

In [5]:
import numpy as np
x = np.array([2, 4, 6])
y = np.array([6, 7, 8])
x + y

array([ 8, 11, 14])

In [6]:
x = np.array([[2, 3, 4], [6, 9, 10]])
x.ndim

2

In [7]:
x.dtype

dtype('int32')

In [8]:
y = np.array([[1.0, 2],[3, 4]])
y.dtype

dtype('float64')

In [13]:
z = np.array([[2, 5], [7, 9]], float).dtype
z

dtype('float64')

In [15]:
y = np.array([[2, 4], [5, 7]])
y.shape

(2, 2)

In [16]:
s = np.array([2, 4, 7, 8, 9])
s.sum()

30

In [21]:
x = np.array([1, 2, 3, 4, 5, 6])
print('beginning x:\n', x)
x_reshape = x.reshape((2, 3))
print('reshaped x:\n', x_reshape)

beginning x:
 [1 2 3 4 5 6]
reshaped x:
 [[1 2 3]
 [4 5 6]]


In [23]:
x_reshape[0, 2]
x_reshape[0, 0]

1

In [24]:
print('x before we modify x_reshape:\n', x)
print('x_reshape before we modify x_reshape:\n', x_reshape)
x_reshape[0, 0] = 5
print('x_reshape after we modify its top left element:\n',
x_reshape)
print('x after we modify top left element of x_reshape:\n', x)

x before we modify x_reshape:
 [1 2 3 4 5 6]
x_reshape before we modify x_reshape:
 [[1 2 3]
 [4 5 6]]
x_reshape after we modify its top left element:
 [[5 2 3]
 [4 5 6]]
x after we modify top left element of x_reshape:
 [5 2 3 4 5 6]
