# Introduction Lab

In [2]:
print('fit a model with', 11, 'variables')
x = [3, 4, 5]
x

[3, 4, 5]

In [3]:
y = [4, 9, 7]
x + y

[3, 4, 5, 4, 9, 7]

### numpy Module

In [3]:
import numpy as np
x = np.array([2, 4, 6])
y = np.array([6, 7, 8])
x + y

array([ 8, 11, 14])

In [6]:
x = np.array([[2, 3, 4], [6, 9, 10]])
x.ndim

2

In [7]:
x.dtype

dtype('int32')

In [4]:
y = np.array([[1.0, 2],[3, 4]])
y.dtype

dtype('float64')

In [13]:
z = np.array([[2, 5], [7, 9]], float).dtype
z

dtype('float64')

In [15]:
y = np.array([[2, 4], [5, 7]])
y.shape

(2, 2)

In [16]:
s = np.array([2, 4, 7, 8, 9])
s.sum()

30

In [5]:
x = np.array([1, 2, 3, 4, 5, 6])
print('beginning x:\n', x)
x_reshape = x.reshape((2, 3))
print('reshaped x:\n', x_reshape)

beginning x:
 [1 2 3 4 5 6]
reshaped x:
 [[1 2 3]
 [4 5 6]]


In [6]:
x_reshape[0, 2]
x_reshape[0, 0]

1

In [24]:
print('x before we modify x_reshape:\n', x)
print('x_reshape before we modify x_reshape:\n', x_reshape)
x_reshape[0, 0] = 5
print('x_reshape after we modify its top left element:\n',
x_reshape)
print('x after we modify top left element of x_reshape:\n', x)

x before we modify x_reshape:
 [1 2 3 4 5 6]
x_reshape before we modify x_reshape:
 [[1 2 3]
 [4 5 6]]
x_reshape after we modify its top left element:
 [[5 2 3]
 [4 5 6]]
x after we modify top left element of x_reshape:
 [5 2 3 4 5 6]


### Shape, Dimension and Transponse

In [29]:
sh = x_reshape.shape
dim = x_reshape.ndim
tran = x_reshape.T
print('shape:', sh, '\ndimension:', dim, '\nTransponse:', tran)
type(sh) == tuple
np.sqrt(x_reshape)
x_reshape ** 2

shape: (2, 3) 
dimension: 2 
Transponse: [[1 4]
 [2 5]
 [3 6]]


array([[ 1,  4,  9],
       [16, 25, 36]])

### Random Normal
##### np.random.normal(loc, scale, size). all the argument are keyword argument:: 
- loc(mean) = 0 default
- scale(standar deviation) = 1 default 
- size can be a number greater than or equal to 1

##### We now generate 50 independent random variables from a N(0, 1) distribution.
<image src='math.png' style='height:400px;width:900px'>

In [46]:
# import os
# cwd = os.getcwd()
# print(cwd)
x = np.random.normal(size = 50)
x

array([-1.49830216,  1.00020156, -0.2087169 ,  0.05626582,  0.12588278,
       -0.47297707, -0.1782713 ,  0.2554321 , -1.0012583 , -1.08945038,
        0.47855255, -0.92243626,  0.54413921,  1.06435246, -0.78279541,
        0.28472918, -0.18963421, -2.6533644 , -0.8764672 , -0.67881927,
        0.59265071,  0.54047326,  0.66070599,  0.42559894, -0.95668698,
       -0.98548632, -1.1454082 ,  0.27326587, -0.2638351 ,  1.68185487,
       -0.90560726,  1.81960969,  0.93968161,  0.26450128,  0.18634301,
        1.97056729,  0.11078337, -0.85032591, -0.29966979,  2.01332623,
       -0.09163257,  0.09148395, -0.91953342, -0.66451776,  0.81016511,
        0.47408043,  1.23089998,  0.23379142,  0.12667472,  2.4119697 ])

In [49]:
y = x + np.random.normal(loc = 50, scale = 1, size= 50)
y

array([48.57736291, 50.25195587, 50.47644009, 49.21859064, 49.12164258,
       48.31469731, 49.51854393, 50.17821752, 48.02213912, 46.39396074,
       51.22146438, 47.54776447, 51.00855751, 51.8232641 , 48.91815956,
       49.10940584, 52.08503085, 46.36113445, 47.69245118, 49.7538723 ,
       51.29907183, 51.35990644, 50.40243018, 50.53533057, 48.27162732,
       49.28167248, 49.5184367 , 50.04721649, 48.54535728, 50.83036109,
       49.13048889, 51.96066749, 49.73070959, 50.93025833, 48.51121314,
       53.22968281, 50.26326549, 48.12014684, 49.38869718, 50.85993709,
       50.00738617, 48.78943678, 47.85267408, 50.34573125, 48.07726777,
       51.77701473, 50.83354102, 48.40480558, 53.00978469, 53.39917525])

##### The np.corrcoef() function computes the correlation matrix between x and y. The off-diagonal elements give the correlation between x and y.

In [51]:
corr = np.corrcoef(x, y)
corr

array([[1.        , 0.73390722],
       [0.73390722, 1.        ]])

##### In order to ensure that our code provides exactly the same results each time it is run, we can set a random seed using the np.random.default_rng() function

In [72]:
rng = np.random.default_rng(1000)
print(rng.normal(loc = 2, scale=5, size=6))
rng2 = np.random.default_rng(1000)
print(rng2.normal(loc = 2, scale=5, size=6))

[ 0.39334897 -0.42830739 10.40029064 11.85263441  2.77591831 -4.28882724]
[ 0.39334897 -0.42830739 10.40029064 11.85263441  2.77591831 -4.28882724]


The np.mean(), np.var(), and np.std() functions can be used to compute
the mean, variance, and standard deviation of arrays. These functions are
also available as methods on the arrays:

In [82]:
# mean
rng = np.random.default_rng(3)
y = rng.standard_normal(10)
np.mean(y), y.mean()

(-0.1126795190952861, -0.1126795190952861)

In [83]:
np.var(y), y.var(), np.mean((y - np.mean(y)) ** 2)

(2.7243406406465125, 2.7243406406465125, 2.7243406406465125)

In [86]:
# standard deviation
np.std(y), np.sqrt(np.var(y)), np.sqrt(np.mean((y - np.mean(x))**2))

(1.6505576756498128, 1.6505576756498128, 1.6596342224105576)