### Rescale Data

In [1]:
from sklearn.preprocessing import MinMaxScaler
from numpy import set_printoptions
from pandas import read_csv
filename = 'data/diabetes.csv'

names = ['preg', 'plas', 'pres', 'skin', 'test', 'mass', 'pedi', 'age', 'class']
dataframe = read_csv(filename, names=names)
array = dataframe.values[1:]
X = array[:, 0:8]
X
Y = array[:, 8]
Y
scaler = MinMaxScaler(feature_range=(0,1))
rescaledX =scaler.fit_transform(X)
set_printoptions(precision=2)
print(rescaledX[0: 5, :])

[[0.35 0.74 0.59 0.35 0.   0.5  0.23 0.48]
 [0.06 0.43 0.54 0.29 0.   0.4  0.12 0.17]
 [0.47 0.92 0.52 0.   0.   0.35 0.25 0.18]
 [0.06 0.45 0.54 0.23 0.11 0.42 0.04 0.  ]
 [0.   0.69 0.33 0.35 0.2  0.64 0.94 0.2 ]]
