In [10]:
import numpy as np
my_list1 = [1, 2, 3, 4]
my_array1 = np.array(my_list1)
print(my_array1)
my_list2 = [11, 22, 33, 44]
my_array2 = np.array(my_list2)
print(my_array2)
my_lists = [my_list1, my_list2]
my_arrays = np.array(my_lists)
print(my_arrays)
print(my_arrays.shape)
print(my_arrays.dtype)

#
my_array_2 = np.array(([1, '', 3], [4, 5, 6]))
print(my_array_2)
print(my_array_2.shape)
print(my_array_2.dtype)


[1 2 3 4]
[11 22 33 44]
[[ 1  2  3  4]
 [11 22 33 44]]
(2, 4)
int32
[['1' '' '3']
 ['4' '5' '6']]
(2, 3)
<U11


In [20]:
import numpy as np
#special array

zeros_array = np.zeros(5)
print(zeros_array)
ones_array = np.ones((5, 5))
print(ones_array)

#identity array
eye_array = np.eye(4, 4)
print(eye_array)
#a range
use_array = np.arange(10, 81, 20)
print(use_array)
print(np.empty(5))
print(np.empty((3,4)))


[0. 0. 0. 0. 0.]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[10 30 50 70]
[0. 0. 0. 0. 0.]
[[1.31915030e-311 3.16202013e-322 0.00000000e+000 0.00000000e+000]
 [1.08221785e-312 3.34885231e-033 5.98655434e+174 2.10581354e-076]
 [9.38871428e+165 2.34244676e-056 9.28166337e-072 6.15910201e+170]]


In [3]:
import numpy as np
array1 = np.array([[1,2,3], [100, 15, 200]])
print(array1 + array1)
print(array1 * array1)
print(array1 - array1)
print(array1 / array1)
print(1 / array1)
print(array1 ** 2)

[[  2   4   6]
 [200  30 400]]
[[    1     4     9]
 [10000   225 40000]]
[[0 0 0]
 [0 0 0]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[1.         0.5        0.33333333]
 [0.01       0.06666667 0.005     ]]
[[    1     4     9]
 [10000   225 40000]]


In [12]:
import numpy as np
my_arange = np.arange(11)
print(my_arange)
slice_arange = my_arange[0:5]
print(slice_arange)
slice_arange[:] = 100
print(slice_arange)
slice_arange[0:2] = 200
print(slice_arange)
slice_copy = slice_arange[:]
print(slice_arange)
slice_arange1 = slice_arange.copy()
print('slice: ', slice_arange == slice_arange1)
print([] == [])
print([4, 7] == [4, 7])
print(set() == {2, 3})
print([2, 4, 6] == [2, 4])
array1 = np.arange(1)
array2 = np.arange(1)
print(array1 == array2)


[ 0  1  2  3  4  5  6  7  8  9 10]
[0 1 2 3 4]
[100 100 100 100 100]
[200 200 100 100 100]
[200 200 100 100 100]
slice:  [ True  True  True  True  True]
True
True
False
False
[ True]


In [18]:
import numpy as np
arr_2d = np.array(([3, 4, 5], [6, 7, 9], [1, 2, 8]))
print(arr_2d)
arr_2d[0, 0] = 100
arr_2d[1, 1] = 100
arr_2d[2, 2] = 100
print(arr_2d)


[[3 4 5]
 [6 7 9]
 [1 2 8]]
[[100   4   5]
 [  6 100   9]
 [  1   2 100]]


In [63]:
arr = []
for row in range(3):
    arr1 = []
    for col in range(3):
        arr1.append(col)
    arr.append(arr1)
print(arr)


[[0, 1, 2], [0, 1, 2], [0, 1, 2]]


In [19]:
import numpy as np
arr = []
num = 0
count = 0
for row in range(6):
    inner_arr = []
    if count == 0:
        num += 0
    else:
        num += 4
    for col in range(6):
        inner_arr.append(num)
        num += 1
    arr.append(inner_arr)
    count += 1
print(arr)
print(arr[0][3:5])
print(arr[:][2])
print(arr[:][0])
print(arr[2::2][::2])
for num in range(6):
    if num % 2 == 0:
        print(arr[:][num])


[0, 1, 2, 3, 4, 5]
[20, 21, 22, 23, 24, 25]
[40, 41, 42, 43, 44, 45]
