In [10]:
import numpy as np
my_list1 = [1, 2, 3, 4]
my_array1 = np.array(my_list1)
print(my_array1)
my_list2 = [11, 22, 33, 44]
my_array2 = np.array(my_list2)
print(my_array2)
my_lists = [my_list1, my_list2]
my_arrays = np.array(my_lists)
print(my_arrays)
print(my_arrays.shape)
print(my_arrays.dtype)

#
my_array_2 = np.array(([1, '', 3], [4, 5, 6]))
print(my_array_2)
print(my_array_2.shape)
print(my_array_2.dtype)


[1 2 3 4]
[11 22 33 44]
[[ 1  2  3  4]
 [11 22 33 44]]
(2, 4)
int32
[['1' '' '3']
 ['4' '5' '6']]
(2, 3)
<U11


In [19]:
import numpy as np
#special array

zeros_array = np.zeros(5)
print(zeros_array)
ones_array = np.ones((5, 5))
print(ones_array)

#identity array
eye_array = np.eye(4, 4)
print(eye_array)
#a range
use_array = np.arange(10, 81, 20)
print(use_array)
print(np.empty(5))
print(np.empty((3,4)))


[0. 0. 0. 0. 0.]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[10 30 50 70]
[0. 0. 0. 0. 0.]
