In [4]:
import numpy as np
z = np.zeros(4)
print(z)
print(z.shape)
z.shape = (2, 2)
z

[0. 0. 0. 0.]
(4,)


array([[0., 0.],
       [0., 0.]])

In [8]:
zeroes_ = np.zeros(4)
zeroes_
zeroes_.shape = (2, 2)
zeroes_

array([[0., 0.],
       [0., 0.]])

In [10]:
linspace_ = np.linspace(2, 5, 5)
linspace_

array([2.  , 2.75, 3.5 , 4.25, 5.  ])

In [13]:
z = np.eye(2)
z

array([[1., 0.],
       [0., 1.]])

In [24]:
z = np.array([[1, 2], [3, 4]])
print(z)
print(z[0, 0])
print(z[1, 1])
print(z[1, :])
print(z[0, :])
print(z[:, 0])


[[1 2]
 [3 4]]
1
4
[3 4]
[1 2]
[1 3]


In [25]:
z = np.empty(3)
z

array([1.05531506e-311, 0.00000000e+000, 6.47591605e-319])

In [26]:
z[:] = 56
z

array([56., 56., 56.])

In [38]:
a = np.array((4, 3, 2, 1))
a.sort()
print(a.mean())
print(a.std())
print(a.sum())
print(a.argmax())
print(a.argmin())
print(a.var())

2.5
1.118033988749895
10
3
0
1.25


In [46]:
z = np.array([2, 3, 5])
y = np.array([6, 7, 8])
add = z + y
print(add)
product = z * y
print(product)
div = z / y
print(div)
sub = y - z
print(sub)
dot = z + 3
print(dot)

[ 8 10 13]
[12 21 40]
[0.33333333 0.42857143 0.625     ]
[4 4 3]
[5 6 8]


In [52]:
A = np.ones((2, 2))
B = np.zeros((2, 2))
mul  = A @ B
mul

array([[0., 0.],
       [0., 0.]])