In [4]:
import numpy as np
z = np.zeros(4)
print(z)
print(z.shape)
z.shape = (2, 2)
z

[0. 0. 0. 0.]
(4,)


array([[0., 0.],
       [0., 0.]])

In [8]:
zeroes_ = np.zeros(4)
zeroes_
zeroes_.shape = (2, 2)
zeroes_

array([[0., 0.],
       [0., 0.]])

In [10]:
linspace_ = np.linspace(2, 5, 5)
linspace_

array([2.  , 2.75, 3.5 , 4.25, 5.  ])

In [13]:
z = np.eye(2)
z

array([[1., 0.],
       [0., 1.]])

In [21]:
z = np.array([[1, 2], [3, 4]])
print(z)
print(z[0, 0])
print(z[1, 1])
print(z[1, :])
print(z[0, :])
print(z[:, 0])


[[1 2]
 [3 4]]
1
4
[3 4]
[1 2]
[1 3]
